name: Jenkins Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      url:
        description: 'URL del repositorio donde se encuentra el Jenkinsfile'
        required: true
    
      path:
        description: 'Path del repositorio donde se encuentra el Jenkinsfile'
        required: true
        default: 'JenkinsFile'

jobs:
  parse_jenkinsfile:
    name: Parse Jenkinsfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.4'
          cache: 'pip'
      - name: install python Libraries
        run: pip install -r requirements.txt
    
      - name: Execute python script
        run: python Jenkins-parse-data.py 